
WITH Functions AS (
    SELECT 20 AS X, 20 AS Y UNION ALL
    SELECT 20 AS X, 21 AS Y UNION ALL
    SELECT 20 AS X, 23 AS Y UNION ALL
    SELECT 22 AS X, 23 AS Y UNION ALL
    SELECT 21 AS X, 20 AS Y
)

SELECT f1.X, f1.Y
FROM Functions f1
JOIN Functions f2 ON f1.X = f2.Y AND f1.Y = f2.X
WHERE f1.X <= f1.Y
ORDER BY f1.X, f1.Y;
